#!/bin/sh

export NATS_SERVER_HOME=${PWD}

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NATS_SERVER_HOME/dist

sh $NATS_SERVER_HOME/utility/run_nodejs.sh &

sleep 1

/usr/bin/java -cp $NATS_SERVER_HOME/dist/nats-server.jar:$NATS_SERVER_HOME/dist/nats-shared.jar:$NATS_SERVER_HOME/dist/rmiio-2.1.2.jar:$NATS_SERVER_HOME/dist/commons-logging-1.2.jar -Djava.library.path=$NATS_SERVER_HOME/dist -Xmx768m NATSServer 2017 $1
